version: "3.9"

services:

  api:
    container_name: api_container
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./api
        target: /opt/api

volumes:
  api: {}
