version: "3.9"

services:
  postgres:
    image: 'postgres:12.2'
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=user-django
      - POSTGRES_DB=my-test
      - POSTGRES_PASSWORD=password321
    volumes:
      - 'pgdata-backend:/var/lib/postgresql/data'

  api:
    depends_on:
      - postgres
    container_name: api_container
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./api
        target: /opt/api

volumes:
  api: {}
  pgdata-backend: {}
